Add a MultipartRequest and a MultipartWrapper for parsing multipart requests.
This implementation requires that both commons-fileupload and commons-io be present in the classpath.
There are actually no check at runtime so be careful with NoClassDefFoundError.

Issue #7